export type IntegrationEdition = "business" | "workspace" | "student";
export type IntegrationReadiness = "live" | "configured" | "buildable" | "approval_required";

export interface IntegrationCatalogItem {
  key: string;
  name: string;
  summary: string;
  editions: IntegrationEdition[];
  readiness: IntegrationReadiness;
  destinations: { label: string; href: string }[];
}

export const INTEGRATION_CATALOG: IntegrationCatalogItem[] = [
  { key: "microsoft", name: "Microsoft 365", summary: "Workplace and Business connect Outlook Mail, Calendar, OneDrive and Teams to their real destinations.", editions: ["business", "workspace"], readiness: "live", destinations: [{ label: "Outlook Mail", href: "/communications" }, { label: "Calendar", href: "/calendar" }, { label: "OneDrive files", href: "/documents" }, { label: "Teams meetings", href: "/meetings" }] },
  { key: "microsoft", name: "Microsoft 365 for Students", summary: "Student connects Outlook Mail and OneDrive files without requesting Calendar or Teams permissions.", editions: ["student"], readiness: "live", destinations: [{ label: "Outlook Mail", href: "/communications" }, { label: "OneDrive files", href: "/documents" }] },
  { key: "google", name: "Google Workspace", summary: "Business connects Google Calendar, sends only user-authored Gmail messages, lets users choose specific Drive files, and creates requested Sheets reports without inbox or broad Drive access.", editions: ["business"], readiness: "live", destinations: [{ label: "Calendar", href: "/calendar" }, { label: "Gmail sending", href: "/communications" }, { label: "Selected Drive files", href: "/documents" }, { label: "Sheets reports", href: "/analytics" }] },
  { key: "slack", name: "Slack", summary: "The Slack app is registered. Channel mirroring and notifications are the remaining product work.", editions: ["business"], readiness: "configured", destinations: [{ label: "Communications", href: "/communications" }, { label: "Automations", href: "/automation" }] },
  { key: "slack", name: "Slack", summary: "The Slack app is registered. Workplace channel mirroring into Communications is the remaining product work.", editions: ["workspace"], readiness: "configured", destinations: [{ label: "Communications", href: "/communications" }] },
  { key: "zoom", name: "Zoom", summary: "Optional meeting-link pathway is available; automatic OAuth creation is deferred until a clear product use case requires it.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "Meetings", href: "/meetings" }] },
  { key: "quickbooks", name: "QuickBooks Online", summary: "Business-only accounting sync for revenue, expenses and invoice status. Intuit developer onboarding and production approval are required.", editions: ["business"], readiness: "buildable", destinations: [{ label: "Finance", href: "/finance" }, { label: "Analytics", href: "/analytics" }] },
  { key: "toast", name: "Toast POS", summary: "Planned read-only sales, menu and transaction feed; Toast partner approval is required.", editions: ["business"], readiness: "approval_required", destinations: [{ label: "Finance", href: "/finance" }, { label: "Inventory", href: "/inventory" }, { label: "Analytics", href: "/analytics" }] },
  { key: "square", name: "Square POS", summary: "Planned read-only payments, catalog and order feed for Finance, Inventory and Analytics.", editions: ["business"], readiness: "buildable", destinations: [{ label: "Finance", href: "/finance" }, { label: "Inventory", href: "/inventory" }, { label: "Analytics", href: "/analytics" }] },
  { key: "stripe", name: "Stripe", summary: "Planned read-only payment and payout visibility; customer integration credentials remain separate from 3Stone billing.", editions: ["business"], readiness: "buildable", destinations: [{ label: "Finance", href: "/finance" }, { label: "Analytics", href: "/analytics" }] },
  { key: "calendly", name: "Calendly", summary: "Planned read-only booking feed into Calendar and Meetings.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "Calendar", href: "/calendar" }, { label: "Meetings", href: "/meetings" }] },
  { key: "calendly", name: "Calendly", summary: "Planned read-only booking feed into the Student Calendar.", editions: ["student"], readiness: "buildable", destinations: [{ label: "Calendar", href: "/calendar" }] },
  { key: "dropbox", name: "Dropbox Business", summary: "Planned read-only file browser. Files stay in Dropbox and open from Documents.", editions: ["business", "workspace", "student"], readiness: "buildable", destinations: [{ label: "Documents", href: "/documents" }] },
  { key: "jobber", name: "Jobber", summary: "Planned read-only customer, job and scheduling feed for field-service businesses.", editions: ["business"], readiness: "buildable", destinations: [{ label: "CRM", href: "/crm" }, { label: "Projects", href: "/projects" }, { label: "Calendar", href: "/calendar" }] },
  { key: "housecall-pro", name: "Housecall Pro", summary: "Planned read-only customer, job and scheduling feed for home-service businesses.", editions: ["business"], readiness: "buildable", destinations: [{ label: "CRM", href: "/crm" }, { label: "Projects", href: "/projects" }, { label: "Calendar", href: "/calendar" }] },
  { key: "servicetitan", name: "ServiceTitan", summary: "Planned enterprise field-service feed for customers, jobs, schedules and reporting; vendor access is required.", editions: ["business"], readiness: "approval_required", destinations: [{ label: "CRM", href: "/crm" }, { label: "Projects", href: "/projects" }, { label: "Calendar", href: "/calendar" }, { label: "Analytics", href: "/analytics" }] },
  { key: "hubspot", name: "HubSpot", summary: "Planned read-only contact, company and deal sync into CRM.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "CRM", href: "/crm" }] },
  { key: "salesforce", name: "Salesforce", summary: "Planned read-only account, contact and opportunity sync into CRM.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "CRM", href: "/crm" }] },
  { key: "mailchimp", name: "Mailchimp", summary: "Planned read-only audience visibility in CRM; campaign delivery remains in Mailchimp.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "CRM", href: "/crm" }] },
  { key: "teams", name: "Microsoft Teams", summary: "Included through Microsoft 365 for meeting and communication context.", editions: ["business", "workspace"], readiness: "live", destinations: [{ label: "Communications", href: "/communications" }, { label: "Meetings", href: "/meetings" }] },
  { key: "docusign", name: "DocuSign", summary: "Planned read-only envelope and signature-status visibility beside the related document.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "Documents", href: "/documents" }] },
  { key: "dropbox-sign", name: "Dropbox Sign", summary: "Planned read-only signature-request status alongside Documents.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "Documents", href: "/documents" }] },
  { key: "chatgpt", name: "OpenAI API", summary: "Connect a workspace-owned OpenAI API key so 3Stone AI uses the customer's provider billing before the included fallback allowance.", editions: ["business", "workspace", "student"], readiness: "live", destinations: [{ label: "Knowledge Center", href: "/knowledge" }, { label: "Documents", href: "/documents" }] },
  { key: "claude", name: "Anthropic API", summary: "Connect a workspace-owned Anthropic API key so 3Stone AI uses the customer's provider billing before the included fallback allowance.", editions: ["business", "workspace", "student"], readiness: "live", destinations: [{ label: "Knowledge Center", href: "/knowledge" }, { label: "Documents", href: "/documents" }] },
  { key: "monday", name: "Monday.com", summary: "Planned read-only boards, groups and items feed into Projects.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "Projects", href: "/projects" }] },
  { key: "asana", name: "Asana", summary: "Planned read-only projects and tasks feed into Projects and Calendar.", editions: ["business", "workspace", "student"], readiness: "buildable", destinations: [{ label: "Projects", href: "/projects" }, { label: "Calendar", href: "/calendar" }] },
  { key: "notion", name: "Notion", summary: "Planned read-only pages and databases feed into Documents and Knowledge Center.", editions: ["business", "workspace", "student"], readiness: "buildable", destinations: [{ label: "Documents", href: "/documents" }, { label: "Knowledge Center", href: "/knowledge" }] },
  { key: "acuity", name: "Acuity Scheduling", summary: "Planned read-only appointment feed into Calendar and Meetings.", editions: ["business", "workspace"], readiness: "buildable", destinations: [{ label: "Calendar", href: "/calendar" }, { label: "Meetings", href: "/meetings" }] },
  { key: "paychex", name: "Paychex Flex", summary: "Business payroll and workforce sync. Paychex must approve 3Stone One before issuing sandbox and production credentials.", editions: ["business"], readiness: "approval_required", destinations: [{ label: "People", href: "/people" }, { label: "Finance", href: "/finance" }] },
  { key: "canvas", name: "Canvas", summary: "Student connection using the school's Canvas URL and personal access token; assignments and course files populate student tools.", editions: ["student"], readiness: "live", destinations: [{ label: "Calendar", href: "/calendar" }, { label: "Projects", href: "/projects" }, { label: "Documents", href: "/documents" }, { label: "Knowledge Center", href: "/knowledge" }] },
  { key: "wildapricot", name: "Wild Apricot", summary: "Nonprofit membership management - connect with your account's own API key (no approval needed); members populate CRM.", editions: ["workspace"], readiness: "live", destinations: [{ label: "CRM", href: "/crm" }] },
  { key: "basecamp", name: "Basecamp", summary: "Real-time project sync is built and ready - needs the founder to register a Basecamp OAuth app (client ID/secret) before anyone can connect.", editions: ["workspace"], readiness: "buildable", destinations: [{ label: "Projects", href: "/projects" }] },
  { key: "linkedin", name: "LinkedIn Jobs", summary: "Track saved job links and confirmation or recruiter email; LinkedIn does not expose a personal application-history API.", editions: ["student"], readiness: "buildable", destinations: [{ label: "Internship & Job Tracker", href: "/job-tracker" }] },
  { key: "handshake", name: "Handshake", summary: "Track internship links and email. Official application API access is institution-scoped and requires Handshake approval.", editions: ["student"], readiness: "approval_required", destinations: [{ label: "Internship & Job Tracker", href: "/job-tracker" }, { label: "Calendar", href: "/calendar" }] },
  { key: "12twenty", name: "12twenty Law Careers", summary: "Law-school job applications, interviews, events and outcomes require an institution-issued API key; students can track 12twenty listing links immediately.", editions: ["student"], readiness: "approval_required", destinations: [{ label: "Internship & Job Tracker", href: "/job-tracker" }, { label: "Calendar", href: "/calendar" }] },
];

export function integrationsForEdition(editionKey: string): IntegrationCatalogItem[] {
  const edition = (editionKey === "workspace" || editionKey === "student" ? editionKey : "business") as IntegrationEdition;
  return INTEGRATION_CATALOG.filter((item) => item.editions.includes(edition));
}
