import type { Job } from "@/types";

export const DEMO_JOBS: Job[] = [
  {
    id: "job_riverside",
    name: "Riverside Remodel",
    client: "Riverside Properties",
    organizationId: "org_riverside",
    status: "in_progress",
    value: 40000,
    startDate: "2026-05-01",
    dueDate: "2026-08-02",
    ownerId: "emp_jane",
    description: "Full interior remodel of the Riverside Properties clubhouse, including electrical, flooring, and a new community kitchen.",
  },
  {
    id: "job_smith",
    name: "Smith Co. Renovation",
    client: "Smith Co.",
    organizationId: "org_smith",
    status: "in_progress",
    value: 28500,
    startDate: "2026-04-10",
    dueDate: "2026-07-01",
    ownerId: "emp_jane",
    overdue: true,
    description: "Storefront renovation for Smith Co.'s flagship retail location, including new signage and ADA-compliant entrance.",
  },
  {
    id: "job_downtown",
    name: "Downtown Lofts Remodel",
    client: "Downtown Lofts",
    organizationId: "org_downtown",
    status: "in_progress",
    value: 52000,
    startDate: "2026-03-15",
    dueDate: "2026-06-28",
    ownerId: "emp_jane",
    overdue: true,
    description: "Common-area remodel across three loft buildings — lobby, elevators, and rooftop deck.",
  },
  {
    id: "job_harbor",
    name: "Harbor View Office Build-out",
    client: "Harbor View LLC",
    organizationId: "org_harbor",
    status: "scheduled",
    value: 95000,
    startDate: "2026-08-01",
    dueDate: "2026-09-15",
    ownerId: "emp_priya",
    description: "Ground-up office build-out for Harbor View's new headquarters floor, 12,000 sq ft.",
  },
  {
    id: "job_maple",
    name: "Maple Street Duplex",
    client: "Maple Street Partners",
    organizationId: "org_maple",
    status: "bid",
    value: 61000,
    startDate: "2026-09-01",
    dueDate: "2026-09-30",
    ownerId: "emp_priya",
    description: "New-construction duplex, bid submitted, awaiting client decision.",
  },
  {
    id: "job_sunridge",
    name: "Sunridge Clinic Expansion",
    client: "Sunridge Medical",
    organizationId: "org_sunridge",
    status: "scheduled",
    value: 73500,
    startDate: "2026-08-15",
    dueDate: "2026-10-10",
    ownerId: "emp_jane",
    description: "Expansion of the Sunridge Medical outpatient clinic, adding four exam rooms.",
  },
  {
    id: "job_fifth",
    name: "Fifth Avenue Retail Fit-out",
    client: "Fifth Ave Retail Group",
    organizationId: "org_fifth",
    status: "in_progress",
    value: 38200,
    startDate: "2026-06-01",
    dueDate: "2026-08-20",
    ownerId: "emp_diego",
    description: "Interior fit-out for a new flagship retail location on Fifth Avenue.",
  },
  {
    id: "job_lincoln",
    name: "Lincoln Park Pergola",
    client: "Lincoln Park HOA",
    organizationId: "org_lincoln",
    status: "done",
    value: 12800,
    startDate: "2026-04-20",
    dueDate: "2026-06-01",
    ownerId: "emp_casey",
    description: "Community pergola and seating area, completed and signed off.",
  },
  {
    id: "job_oakwood",
    name: "Oakwood Warehouse Roof",
    client: "Oakwood Logistics",
    organizationId: "org_oakwood",
    status: "done",
    value: 46000,
    startDate: "2026-03-01",
    dueDate: "2026-05-15",
    ownerId: "emp_taylor",
    description: "Full roof replacement on Oakwood's 40,000 sq ft distribution warehouse.",
  },
  {
    id: "job_cedar",
    name: "Cedar Hills Custom Home",
    client: "The Whitfield Family",
    organizationId: "org_whitfield",
    status: "bid",
    value: 210000,
    startDate: "2026-12-01",
    dueDate: "2026-12-01",
    ownerId: "emp_priya",
    description: "Ground-up custom home, 4,200 sq ft, bid submitted.",
  },
];
