import type { Announcement, Department, Employee } from "@/types";

export const DEMO_EMPLOYEES: Employee[] = [
  {
    id: "emp_jane",
    name: "Jane Dorsey",
    initials: "JD",
    title: "Project Manager",
    department: "Construction",
    email: "jane.dorsey@acmeconstruction.com",
    phone: "(555) 201-4471",
    hireDate: "2022-03-14",
    role: "Manager",
    overdueCount: 2,
    overtimeHours: 11,
    status: "active",
  },
  {
    id: "emp_marcus",
    name: "Marcus Webb",
    initials: "MW",
    title: "Electrician",
    department: "Field",
    email: "marcus.webb@acmeconstruction.com",
    phone: "(555) 201-8823",
    hireDate: "2023-06-01",
    role: "Member",
    overdueCount: 1,
    status: "active",
  },
  {
    id: "emp_priya",
    name: "Priya Shah",
    initials: "PS",
    title: "Lead Estimator",
    department: "Estimating",
    email: "priya.shah@acmeconstruction.com",
    phone: "(555) 201-3390",
    hireDate: "2026-07-04",
    role: "Manager",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_diego",
    name: "Diego Ramirez",
    initials: "DR",
    title: "Technician",
    department: "Field",
    email: "diego.ramirez@acmeconstruction.com",
    phone: "(555) 201-7712",
    hireDate: "2024-01-08",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_sam",
    name: "Sam Okafor",
    initials: "SO",
    title: "Office Manager",
    department: "Admin",
    email: "sam.okafor@acmeconstruction.com",
    phone: "(555) 201-5541",
    hireDate: "2021-11-19",
    role: "Admin",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_taylor",
    name: "Taylor Brooks",
    initials: "TB",
    title: "Technician",
    department: "Field",
    email: "taylor.brooks@acmeconstruction.com",
    phone: "(555) 201-6650",
    hireDate: "2023-09-25",
    role: "Member",
    overdueCount: 0,
    status: "away",
  },
  {
    id: "emp_morgan",
    name: "Morgan Lee",
    initials: "ML",
    title: "Accountant",
    department: "Finance",
    email: "morgan.lee@acmeconstruction.com",
    phone: "(555) 201-9902",
    hireDate: "2022-08-15",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_casey",
    name: "Casey Nguyen",
    initials: "CN",
    title: "Technician",
    department: "Field",
    email: "casey.nguyen@acmeconstruction.com",
    phone: "(555) 201-2287",
    hireDate: "2024-04-02",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
];

export const DEMO_DEPARTMENTS: Department[] = [
  { id: "dept_construction", name: "Construction", leadId: "emp_jane" },
  { id: "dept_field", name: "Field", leadId: "emp_marcus" },
  { id: "dept_estimating", name: "Estimating", leadId: "emp_priya" },
  { id: "dept_admin", name: "Admin", leadId: "emp_sam" },
  { id: "dept_finance", name: "Finance", leadId: "emp_morgan" },
];

export const DEMO_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann_1",
    title: "Riverside Properties signed — kickoff next week",
    body: "Great news — Riverside Properties signed the clubhouse remodel contract. Jane will run kickoff with the field team Monday morning.",
    authorId: "emp_sam",
    at: "2 days ago",
  },
  {
    id: "ann_2",
    title: "Welcome Priya Shah, Lead Estimator",
    body: "Please join us in welcoming Priya Shah to the Estimating team. Priya joins us from a regional GC and will be leading bids on Harbor View, Maple Street, and Cedar Hills.",
    authorId: "emp_sam",
    department: "Estimating",
    at: "3 days ago",
  },
  {
    id: "ann_3",
    title: "Updated safety check-in process for job sites",
    body: "Starting this week, all field staff should check in via the site log at the start and end of every shift. See the Knowledge Center for the updated SOP.",
    authorId: "emp_sam",
    department: "Field",
    at: "5 days ago",
  },
  {
    id: "ann_4",
    title: "Q2 numbers are in — revenue up 12%",
    body: "Thanks to everyone's work this quarter — revenue is up 12% over last quarter, driven largely by the Riverside and Harbor View contracts.",
    authorId: "emp_morgan",
    at: "1 week ago",
  },
  {
    id: "ann_5",
    title: "New vendor account: Ferguson Supply",
    body: "We've opened a new materials account with Ferguson Supply for faster turnaround on plumbing fixtures. Reach out to Sam for account details.",
    authorId: "emp_sam",
    department: "Admin",
    at: "1 week ago",
  },
];

export function getEmployeeName(id: string) {
  return DEMO_EMPLOYEES.find((e) => e.id === id)?.name ?? "Unknown";
}

export function getEmployeeInitials(id: string) {
  return DEMO_EMPLOYEES.find((e) => e.id === id)?.initials ?? "?";
}
