import type {
  ActivityItem,
  Deal,
  Employee,
  IndustryDataset,
  Invoice,
  Job,
  Organization,
  Person,
} from "@/types";

const ORGANIZATIONS: Organization[] = [
  { id: "org_law_whitcombe", name: "The Whitcombe Family", domain: "", industry: "Individual Client", ownerId: "emp_law_blackwell", createdAt: "2025-09-12" },
  { id: "org_law_pearson", name: "Pearson & Vance Realty", domain: "pearsonvancerealty.com", industry: "Real Estate", ownerId: "emp_law_voss", createdAt: "2025-03-01" },
  { id: "org_law_ironclad", name: "Ironclad Fabrication LLC", domain: "ironcladfab.com", industry: "Manufacturing", ownerId: "emp_law_halloran", createdAt: "2025-11-20" },
  { id: "org_law_delgado", name: "Marisol Delgado", domain: "", industry: "Individual Client", ownerId: "emp_law_nataraj", createdAt: "2026-01-15" },
  { id: "org_law_brightpath", name: "BrightPath Logistics Inc.", domain: "brightpathlogistics.com", industry: "Logistics", ownerId: "emp_law_nataraj", createdAt: "2025-06-05" },
  { id: "org_law_summit", name: "Summit Ridge Homeowners Association", domain: "summitridgehoa.org", industry: "Property Association", ownerId: "emp_law_halloran", createdAt: "2024-12-10" },
  { id: "org_law_kessler", name: "Adam Kessler", domain: "", industry: "Individual Client", ownerId: "emp_law_blackwell", createdAt: "2026-05-01" },
  { id: "org_law_novak", name: "Novak & Ellis Dental Group", domain: "novakellisdental.com", industry: "Healthcare", ownerId: "emp_law_halloran", createdAt: "2026-06-30" },
];

const PEOPLE: Person[] = [
  { id: "per_law_whitcombe", firstName: "Grant", lastName: "Whitcombe", email: "grant.whitcombe@gmail.com", phone: "(555) 618-2201", organizationId: "org_law_whitcombe", personType: "customer", ownerId: "emp_law_blackwell", createdAt: "2025-09-12", lastContact: "2 weeks ago" },
  { id: "per_law_pearson", firstName: "Denise", lastName: "Pearson", email: "denise.pearson@pearsonvancerealty.com", phone: "(555) 618-3312", organizationId: "org_law_pearson", personType: "customer", ownerId: "emp_law_voss", createdAt: "2025-03-01", lastContact: "3 days ago" },
  { id: "per_law_ironclad", firstName: "Victor", lastName: "Cho", email: "victor.cho@ironcladfab.com", phone: "(555) 618-4423", organizationId: "org_law_ironclad", personType: "customer", ownerId: "emp_law_halloran", createdAt: "2025-11-20", lastContact: "2 days ago" },
  { id: "per_law_delgado", firstName: "Marisol", lastName: "Delgado", email: "marisol.delgado@outlook.com", phone: "(555) 618-5534", organizationId: "org_law_delgado", personType: "customer", ownerId: "emp_law_nataraj", createdAt: "2026-01-15", lastContact: "3 days ago" },
  { id: "per_law_brightpath", firstName: "Angela", lastName: "Ferris", email: "angela.ferris@brightpathlogistics.com", phone: "(555) 618-6645", organizationId: "org_law_brightpath", personType: "customer", ownerId: "emp_law_nataraj", createdAt: "2025-06-05", lastContact: "Yesterday" },
  { id: "per_law_summit", firstName: "Harold", lastName: "Ng", email: "harold.ng@summitridgehoa.org", phone: "(555) 618-7756", organizationId: "org_law_summit", personType: "customer", ownerId: "emp_law_halloran", createdAt: "2024-12-10", lastContact: "4 days ago" },
  { id: "per_law_kessler", firstName: "Adam", lastName: "Kessler", email: "adam.kessler@gmail.com", phone: "(555) 618-8867", organizationId: "org_law_kessler", personType: "lead", ownerId: "emp_law_blackwell", createdAt: "2026-05-01", lastContact: "5 days ago" },
  { id: "per_law_novak", firstName: "Elaine", lastName: "Novak", email: "elaine.novak@novakellisdental.com", phone: "(555) 618-9978", organizationId: "org_law_novak", personType: "lead", ownerId: "emp_law_halloran", createdAt: "2026-06-30", lastContact: "Today" },
];

const DEALS: Deal[] = [
  { id: "deal_law_whitcombe", personId: "per_law_whitcombe", organizationId: "org_law_whitcombe", title: "Whitcombe — Divorce & Custody Settlement", value: 18000, stage: "won", ownerId: "emp_law_blackwell", expectedCloseDate: "2025-09-15" },
  { id: "deal_law_pearson", personId: "per_law_pearson", organizationId: "org_law_pearson", title: "Pearson & Vance — 400 Elm St. Closing Retainer", value: 12000, stage: "won", ownerId: "emp_law_voss", expectedCloseDate: "2026-05-01" },
  { id: "deal_law_ironclad", personId: "per_law_ironclad", organizationId: "org_law_ironclad", title: "Ironclad Fabrication — Supplier Contract Dispute", value: 65000, stage: "won", ownerId: "emp_law_halloran", expectedCloseDate: "2025-12-01" },
  { id: "deal_law_delgado", personId: "per_law_delgado", organizationId: "org_law_delgado", title: "Delgado — Personal Injury Claim", value: 45000, stage: "won", ownerId: "emp_law_nataraj", expectedCloseDate: "2026-02-10" },
  { id: "deal_law_brightpath", personId: "per_law_brightpath", organizationId: "org_law_brightpath", title: "BrightPath Logistics — Breach of Contract Suit", value: 85000, stage: "won", ownerId: "emp_law_nataraj", expectedCloseDate: "2025-07-01" },
  { id: "deal_law_summit", personId: "per_law_summit", organizationId: "org_law_summit", title: "Summit Ridge HOA — Special Assessment Dispute", value: 22000, stage: "won", ownerId: "emp_law_halloran", expectedCloseDate: "2025-01-05" },
  { id: "deal_law_kessler", personId: "per_law_kessler", organizationId: "org_law_kessler", title: "Kessler — Custody Modification", value: 8500, stage: "contacted", ownerId: "emp_law_blackwell", expectedCloseDate: "2026-07-25" },
  { id: "deal_law_novak", personId: "per_law_novak", organizationId: "org_law_novak", title: "Novak & Ellis — Partnership Dissolution", value: 38000, stage: "new_lead", ownerId: "emp_law_halloran", expectedCloseDate: "2026-08-05" },
];

const JOBS: Job[] = [
  {
    id: "job_law_whitcombe",
    name: "Whitcombe v. Whitcombe",
    client: "The Whitcombe Family",
    organizationId: "org_law_whitcombe",
    status: "done",
    value: 18000,
    startDate: "2025-09-15",
    dueDate: "2026-05-20",
    ownerId: "emp_law_blackwell",
    description: "Contested divorce and child custody matter finalized via mediated settlement in Family Court; parenting plan and asset division approved by the court.",
  },
  {
    id: "job_law_pearson",
    name: "Pearson & Vance — 400 Elm St. Closing",
    client: "Pearson & Vance Realty",
    organizationId: "org_law_pearson",
    status: "in_progress",
    value: 12000,
    startDate: "2026-05-01",
    dueDate: "2026-07-25",
    ownerId: "emp_law_voss",
    description: "Commercial real estate closing for a 6,200 sq ft retail building at 400 Elm Street, including title review, lease assignment, and closing coordination.",
  },
  {
    id: "job_law_ironclad",
    name: "Ironclad v. Meridian Steel Supply",
    client: "Ironclad Fabrication LLC",
    organizationId: "org_law_ironclad",
    status: "in_progress",
    value: 65000,
    startDate: "2025-12-01",
    dueDate: "2026-07-01",
    ownerId: "emp_law_halloran",
    overdue: true,
    description: "Breach-of-contract suit against a former steel supplier for failure to deliver under a fixed-price purchase order; filed in Superior Court and currently behind schedule in written discovery.",
  },
  {
    id: "job_law_delgado",
    name: "Delgado Personal Injury Claim",
    client: "Marisol Delgado",
    organizationId: "org_law_delgado",
    status: "scheduled",
    value: 45000,
    startDate: "2026-02-10",
    dueDate: "2026-08-15",
    ownerId: "emp_law_nataraj",
    description: "Personal injury claim arising from a rear-end collision; treating physician records gathered, mediation scheduled with the at-fault driver's insurer.",
  },
  {
    id: "job_law_brightpath",
    name: "BrightPath Logistics v. Carrier Solutions",
    client: "BrightPath Logistics Inc.",
    organizationId: "org_law_brightpath",
    status: "in_progress",
    value: 85000,
    startDate: "2025-07-01",
    dueDate: "2026-06-30",
    ownerId: "emp_law_nataraj",
    overdue: true,
    description: "Federal breach-of-contract suit against a former freight carrier for failure to meet delivery service levels; fact discovery is past deadline with a deposition already on the calendar.",
  },
  {
    id: "job_law_summit",
    name: "Summit Ridge HOA Assessment Dispute",
    client: "Summit Ridge Homeowners Association",
    organizationId: "org_law_summit",
    status: "done",
    value: 22000,
    startDate: "2025-01-05",
    dueDate: "2026-03-01",
    ownerId: "emp_law_halloran",
    description: "Dispute over a $180,000 special assessment for roof repairs; resolved through a negotiated payment plan and amended HOA bylaws.",
  },
  {
    id: "job_law_kessler",
    name: "Kessler Custody Modification",
    client: "Adam Kessler",
    organizationId: "org_law_kessler",
    status: "bid",
    value: 8500,
    startDate: "2026-06-25",
    dueDate: "2026-07-20",
    ownerId: "emp_law_blackwell",
    description: "Petition to modify an existing custody order following the client's relocation for work; initial filing being prepared for family court.",
  },
  {
    id: "job_law_novak",
    name: "Novak & Ellis Partnership Dissolution",
    client: "Novak & Ellis Dental Group",
    organizationId: "org_law_novak",
    status: "bid",
    value: 38000,
    startDate: "2026-06-30",
    dueDate: "2026-08-01",
    ownerId: "emp_law_halloran",
    description: "Dispute between dental practice co-owners over practice valuation and buyout terms ahead of a planned partnership dissolution; engagement letter and initial document requests in progress.",
  },
];

const INVOICES: Invoice[] = [
  { id: "inv_law_2178", number: "INV-2178", client: "The Whitcombe Family", amount: 4200, status: "paid", issuedDate: "2026-04-18", dueDate: "2026-05-02" },
  { id: "inv_law_2183", number: "INV-2183", client: "Marisol Delgado", amount: 6000, status: "paid", issuedDate: "2026-04-25", dueDate: "2026-05-09" },
  { id: "inv_law_2188", number: "INV-2188", client: "BrightPath Logistics Inc.", amount: 15600, status: "paid", issuedDate: "2026-05-10", dueDate: "2026-05-24" },
  { id: "inv_law_2192", number: "INV-2192", client: "Summit Ridge Homeowners Association", amount: 4200, status: "overdue", issuedDate: "2026-05-18", dueDate: "2026-06-01" },
  { id: "inv_law_2196", number: "INV-2196", client: "Ironclad Fabrication LLC", amount: 8200, status: "paid", issuedDate: "2026-05-29", dueDate: "2026-06-12" },
  { id: "inv_law_2201", number: "INV-2201", client: "Pearson & Vance Realty", amount: 3400, status: "overdue", issuedDate: "2026-05-27", dueDate: "2026-06-27" },
  { id: "inv_law_2210", number: "INV-2210", client: "Adam Kessler", amount: 2500, status: "sent", issuedDate: "2026-06-25", dueDate: "2026-07-25" },
  { id: "inv_law_2214", number: "INV-2214", client: "Novak & Ellis Dental Group", amount: 5400, status: "sent", issuedDate: "2026-07-02", dueDate: "2026-08-01" },
];

const EMPLOYEES: Employee[] = [
  {
    id: "emp_law_halloran",
    name: "Diane Halloran",
    initials: "DH",
    title: "Managing Partner",
    department: "Firm Management",
    email: "diane.halloran@halloranvoss.com",
    phone: "(555) 704-1120",
    hireDate: "2014-03-01",
    role: "Owner",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_law_voss",
    name: "Marcus Voss",
    initials: "MV",
    title: "Partner",
    department: "Real Estate",
    email: "marcus.voss@halloranvoss.com",
    phone: "(555) 704-2231",
    hireDate: "2014-03-01",
    role: "Admin",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_law_nataraj",
    name: "Priya Nataraj",
    initials: "PN",
    title: "Senior Associate",
    department: "Litigation",
    email: "priya.nataraj@halloranvoss.com",
    phone: "(555) 704-3342",
    hireDate: "2019-08-12",
    role: "Manager",
    overdueCount: 1,
    overtimeHours: 6,
    status: "active",
  },
  {
    id: "emp_law_blackwell",
    name: "Owen Blackwell",
    initials: "OB",
    title: "Associate Attorney",
    department: "Family Law",
    email: "owen.blackwell@halloranvoss.com",
    phone: "(555) 704-4453",
    hireDate: "2022-01-10",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_law_reyes",
    name: "Sofia Reyes",
    initials: "SR",
    title: "Associate Attorney",
    department: "Litigation",
    email: "sofia.reyes@halloranvoss.com",
    phone: "(555) 704-5564",
    hireDate: "2026-06-24",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_law_castillo",
    name: "Renee Castillo",
    initials: "RC",
    title: "Senior Paralegal",
    department: "Litigation",
    email: "renee.castillo@halloranvoss.com",
    phone: "(555) 704-6675",
    hireDate: "2017-05-19",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_law_marsh",
    name: "Devon Marsh",
    initials: "DM",
    title: "Paralegal",
    department: "Real Estate",
    email: "devon.marsh@halloranvoss.com",
    phone: "(555) 704-7786",
    hireDate: "2023-09-05",
    role: "Member",
    overdueCount: 0,
    status: "away",
  },
  {
    id: "emp_law_ito",
    name: "Lauren Ito",
    initials: "LI",
    title: "Office Manager",
    department: "Admin",
    email: "lauren.ito@halloranvoss.com",
    phone: "(555) 704-8897",
    hireDate: "2016-11-02",
    role: "Admin",
    overdueCount: 0,
    status: "active",
  },
];

const NOTIFICATIONS: ActivityItem[] = [
  { id: "act_law_1", message: "New intake call scheduled with Novak & Ellis Dental Group", actor: "Lauren Ito", timestamp: "Today", kind: "meeting", module: "CRM" },
  { id: "act_law_2", message: "Complaint filed in Ironclad Fabrication LLC v. Meridian Steel Supply", actor: "Diane Halloran", timestamp: "2 days ago", kind: "document", module: "Cases" },
  { id: "act_law_3", message: "Deposition scheduled for BrightPath Logistics v. Carrier Solutions", actor: "Priya Nataraj", timestamp: "Yesterday", kind: "meeting", module: "Cases" },
  { id: "act_law_4", message: "Settlement offer received in the Delgado personal injury claim", actor: "Priya Nataraj", timestamp: "3 days ago", kind: "deal", module: "CRM" },
  { id: "act_law_5", message: "Invoice INV-2201 (Pearson & Vance Realty) is now 11 days overdue", actor: "System", timestamp: "Today", kind: "invoice", module: "Finance" },
  { id: "act_law_6", message: "Uploaded Kessler-Custody-Modification-Petition.pdf", actor: "Owen Blackwell", timestamp: "2 days ago", kind: "document", module: "Documents" },
  { id: "act_law_7", message: "Case status changed to Active Litigation — BrightPath Logistics v. Carrier Solutions", actor: "Priya Nataraj", timestamp: "1 week ago", kind: "job", module: "Cases" },
  { id: "act_law_8", message: "Scheduled: Summit Ridge HOA board update call", actor: "Diane Halloran", timestamp: "4 days ago", kind: "meeting", module: "Meetings" },
  { id: "act_law_9", message: "Sofia Reyes joined the firm as Associate Attorney", actor: "Lauren Ito", timestamp: "2 weeks ago", kind: "hire", module: "People" },
  { id: "act_law_10", message: "Workflow \"Overdue Invoice Reminder\" ran for INV-2192", actor: "Automation", timestamp: "Today", kind: "automation", module: "Automation" },
  { id: "act_law_11", message: "Retainer fee waiver approved for the Kessler custody matter", actor: "Diane Halloran", timestamp: "Yesterday", kind: "approval", module: "Finance" },
  { id: "act_law_12", message: "Client portal message from Grant Whitcombe re: final settlement documents", actor: "Grant Whitcombe", timestamp: "3 days ago", kind: "message", module: "Communications" },
  { id: "act_law_13", message: "New matter opened: Novak & Ellis Partnership Dissolution", actor: "Diane Halloran", timestamp: "Today", kind: "deal", module: "CRM" },
  { id: "act_law_14", message: "Invoice INV-2188 (BrightPath Logistics Inc.) paid in full", actor: "System", timestamp: "1 week ago", kind: "invoice", module: "Finance" },
  { id: "act_law_15", message: "Case marked Settled/Closed — Whitcombe v. Whitcombe", actor: "Owen Blackwell", timestamp: "2 weeks ago", kind: "job", module: "Cases" },
];

const MONTHLY_BILLABLES: { month: string; revenue: number; overhead: number }[] = [
  { month: "Feb", revenue: 108000, overhead: 79000 },
  { month: "Mar", revenue: 113200, overhead: 81200 },
  { month: "Apr", revenue: 119800, overhead: 83500 },
  { month: "May", revenue: 124600, overhead: 85800 },
  { month: "Jun", revenue: 130500, overhead: 87200 },
  { month: "Jul", revenue: 142300, overhead: 89100 },
];

const REVENUE_MTD = MONTHLY_BILLABLES[MONTHLY_BILLABLES.length - 1].revenue;
const REVENUE_LAST_MONTH = MONTHLY_BILLABLES[MONTHLY_BILLABLES.length - 2].revenue;
const REVENUE_DELTA_PCT = Math.round(((REVENUE_MTD - REVENUE_LAST_MONTH) / REVENUE_LAST_MONTH) * 100);

const TARGET_HOURS_MTD = 1840;
const BILLED_HOURS_MTD = 1435;
const UTILIZATION_PCT = Math.round((BILLED_HOURS_MTD / TARGET_HOURS_MTD) * 100);

const atRiskJobs = JOBS.filter((j) => j.overdue);

export const LAW_FIRM_DATASET: IndustryDataset = {
  profileKey: "law_firm",
  orgName: "Halloran & Voss LLP",
  greetingSubtitle: "Here's what matters at Halloran & Voss LLP today.",
  kpis: [
    {
      key: "billable_revenue_mtd",
      label: "Billable Revenue MTD",
      value: `$${REVENUE_MTD.toLocaleString()}`,
      deltaLabel: `+${REVENUE_DELTA_PCT}% vs last month`,
      tone: "positive",
      trend: MONTHLY_BILLABLES.map((m) => m.revenue),
    },
    {
      key: "billable_utilization",
      label: "Billable Utilization",
      value: `${UTILIZATION_PCT}%`,
      deltaLabel: `${BILLED_HOURS_MTD.toLocaleString()} of ${TARGET_HOURS_MTD.toLocaleString()} target hours billed`,
      tone: "neutral",
      trend: [72, 74, 75, 77, 76, UTILIZATION_PCT],
    },
    {
      key: "cases_at_risk",
      label: "Cases At Risk",
      value: String(atRiskJobs.length),
      deltaLabel: atRiskJobs.map((j) => j.client).join(", ") || "None — all cases on schedule",
      tone: atRiskJobs.length > 0 ? "negative" : "positive",
    },
  ],
  monthlyChart: {
    title: "Billable revenue vs. overhead — 6 months",
    primaryLabel: "Billable Revenue",
    secondaryLabel: "Overhead",
    unit: "currency",
    months: MONTHLY_BILLABLES.map((m) => ({ month: m.month, primary: m.revenue, secondary: m.overhead })),
  },
  breakdownChart: {
    title: "Case stage breakdown",
    segments: [
      { label: "Intake", count: JOBS.filter((j) => j.status === "bid").length },
      { label: "Discovery", count: JOBS.filter((j) => j.status === "scheduled").length },
      { label: "Active Litigation", count: JOBS.filter((j) => j.status === "in_progress").length },
      { label: "Settled/Closed", count: JOBS.filter((j) => j.status === "done").length },
    ],
  },
  organizations: ORGANIZATIONS,
  people: PEOPLE,
  deals: DEALS,
  jobs: JOBS,
  invoices: INVOICES,
  employees: EMPLOYEES,
  notifications: NOTIFICATIONS,
  aiRecommendations: [
    "Ironclad Fabrication LLC's breach-of-contract suit against Meridian Steel Supply has fallen behind on written discovery — file for a short extension before the court sets a compliance deadline.",
    "Invoice INV-2201 ($3,400, Pearson & Vance Realty) is 11 days overdue — a call from Marcus Voss tends to clear real estate retainer balances faster than another email reminder.",
    "Billable utilization is at 78% of the 1,840-hour monthly target — Owen Blackwell has open capacity this week and could take the first pass on the Kessler custody modification petition.",
    "BrightPath Logistics v. Carrier Solutions is the firm's largest active matter at $85,000 and is already past its discovery deadline with a deposition on the calendar — loop in Diane Halloran ahead of the hearing.",
  ],
};
