import type {
  ActivityItem,
  Deal,
  Employee,
  IndustryDataset,
  Invoice,
  Job,
  Organization,
  Person,
} from "@/types";

const ORGANIZATIONS: Organization[] = [
  { id: "org_pm_birchwood", name: "Birchwood Holdings LLC", domain: "birchwoodholdingsllc.com", industry: "Real Estate Investment", ownerId: "emp_pm_diane", createdAt: "2025-01-14" },
  { id: "org_pm_hartley", name: "Hartley Family Trust", domain: "", industry: "Private Landlord", ownerId: "emp_pm_carl", createdAt: "2025-03-02" },
  { id: "org_pm_summit", name: "Summit Ridge HOA", domain: "summitridgehoa.org", industry: "Homeowners Association", ownerId: "emp_pm_diane", createdAt: "2025-04-18" },
  { id: "org_pm_vantage", name: "Vantage Point Investments", domain: "vantagepointinv.com", industry: "Real Estate Investment", ownerId: "emp_pm_marcus", createdAt: "2025-08-05" },
  { id: "org_pm_oldmill", name: "Old Mill Commons LLC", domain: "oldmillcommonsllc.com", industry: "Mixed-Use Real Estate", ownerId: "emp_pm_carl", createdAt: "2025-09-22" },
  { id: "org_pm_kestrel", name: "Kestrel Row Condominiums", domain: "kestrelrowcondos.org", industry: "Condominium Association", ownerId: "emp_pm_diane", createdAt: "2025-11-10" },
  { id: "org_pm_delacroix", name: "Delacroix Family Properties", domain: "delacroixfamilyproperties.com", industry: "Real Estate Investment", ownerId: "emp_pm_carl", createdAt: "2025-09-01" },
];

const PEOPLE: Person[] = [
  { id: "per_pm_alan", firstName: "Alan", lastName: "Cho", email: "alan.cho@birchwoodholdingsllc.com", phone: "(555) 447-2201", organizationId: "org_pm_birchwood", personType: "contact", ownerId: "emp_pm_diane", createdAt: "2025-01-14", lastContact: "4 days ago" },
  { id: "per_pm_carol", firstName: "Carol", lastName: "Renner", email: "carol.renner@gmail.com", phone: "(555) 447-3312", organizationId: "org_pm_hartley", personType: "contact", ownerId: "emp_pm_carl", createdAt: "2025-03-02", lastContact: "6 days ago" },
  { id: "per_pm_janet", firstName: "Janet", lastName: "Ostrowski", email: "j.ostrowski@summitridgehoa.org", phone: "(555) 447-4423", organizationId: "org_pm_summit", personType: "contact", ownerId: "emp_pm_diane", createdAt: "2025-04-18", lastContact: "1 week ago" },
  { id: "per_pm_neil", firstName: "Neil", lastName: "Anders", email: "neil.anders@vantagepointinv.com", phone: "(555) 447-5534", organizationId: "org_pm_vantage", personType: "contact", ownerId: "emp_pm_marcus", createdAt: "2025-08-05", lastContact: "2 days ago" },
  { id: "per_pm_grant", firstName: "Grant", lastName: "Delacroix", email: "grant.delacroix@delacroixfamilyproperties.com", phone: "(555) 447-6645", organizationId: "org_pm_delacroix", personType: "contact", ownerId: "emp_pm_carl", createdAt: "2025-09-01", lastContact: "3 weeks ago" },
  { id: "per_pm_maria", firstName: "Maria", lastName: "Kowalski", email: "maria.kowalski@gmail.com", phone: "(555) 447-7756", organizationId: "org_pm_birchwood", personType: "customer", ownerId: "emp_pm_sofia", createdAt: "2025-08-01", lastContact: "Today" },
  { id: "per_pm_travis", firstName: "Travis", lastName: "Boyd", email: "travis.boyd@outlook.com", phone: "(555) 447-8867", organizationId: null, personType: "lead", ownerId: "emp_pm_marcus", createdAt: "2026-06-20", lastContact: "Yesterday" },
  { id: "per_pm_renee", firstName: "Renee", lastName: "Castillo", email: "renee.castillo@gmail.com", phone: "(555) 447-9978", organizationId: null, personType: "lead", ownerId: "emp_pm_marcus", createdAt: "2026-05-10", lastContact: "3 weeks ago" },
];

const DEALS: Deal[] = [
  { id: "deal_pm_birchwood_mgmt", personId: "per_pm_alan", organizationId: "org_pm_birchwood", title: "Birchwood Holdings LLC — Management Contract Renewal", value: 19200, stage: "won", ownerId: "emp_pm_diane", expectedCloseDate: "2025-12-15" },
  { id: "deal_pm_hartley", personId: "per_pm_carol", organizationId: "org_pm_hartley", title: "Hartley Duplex — Management Contract", value: 6600, stage: "won", ownerId: "emp_pm_carl", expectedCloseDate: "2025-03-10" },
  { id: "deal_pm_summit", personId: "per_pm_janet", organizationId: "org_pm_summit", title: "Summit Ridge HOA — Common Area Management Contract", value: 27000, stage: "won", ownerId: "emp_pm_diane", expectedCloseDate: "2025-05-01" },
  { id: "deal_pm_vantage", personId: "per_pm_neil", organizationId: "org_pm_vantage", title: "Vantage Point Fourplex Portfolio — Management Contract Expansion", value: 34500, stage: "negotiation", ownerId: "emp_pm_marcus", expectedCloseDate: "2026-08-20" },
  { id: "deal_pm_delacroix", personId: "per_pm_grant", organizationId: "org_pm_delacroix", title: "Delacroix Family Properties — Management Contract", value: 15600, stage: "won", ownerId: "emp_pm_carl", expectedCloseDate: "2025-09-10" },
  { id: "deal_pm_birchwood_lease", personId: "per_pm_maria", organizationId: "org_pm_birchwood", title: "The Birchwood Apartments Unit 4B — Lease Renewal", value: 21600, stage: "proposal", ownerId: "emp_pm_priya", expectedCloseDate: "2026-08-01" },
  { id: "deal_pm_travis", personId: "per_pm_travis", organizationId: null, title: "Boyd Sixplex — New Management Contract", value: 10800, stage: "new_lead", ownerId: "emp_pm_marcus", expectedCloseDate: "2026-09-15" },
  { id: "deal_pm_renee", personId: "per_pm_renee", organizationId: null, title: "Castillo Fourplex — Management Contract", value: 9600, stage: "lost", ownerId: "emp_pm_marcus", expectedCloseDate: "2026-06-01" },
];

const JOBS: Job[] = [
  {
    id: "job_pm_birchwood_4b",
    name: "The Birchwood Apartments — Unit 4B",
    client: "Birchwood Holdings LLC",
    organizationId: "org_pm_birchwood",
    status: "in_progress",
    value: 1800,
    startDate: "2025-08-01",
    dueDate: "2026-07-31",
    ownerId: "emp_pm_sofia",
    description: "2BR/1BA, 850 sq ft top-floor unit with in-unit laundry and a private balcony. Tenant Maria Kowalski has been in place since August 2025; a lease renewal offer went out this week for the Aug 1 term.",
  },
  {
    id: "job_pm_birchwood_6c",
    name: "The Birchwood Apartments — Unit 6C",
    client: "Birchwood Holdings LLC",
    organizationId: "org_pm_birchwood",
    status: "bid",
    value: 1750,
    startDate: "2026-07-02",
    dueDate: "2026-08-15",
    ownerId: "emp_pm_priya",
    description: "1BR/1BA, 620 sq ft, freshly renovated with new flooring, quartz counters, and stainless appliances. Listed July 2 — 14 inquiries and 3 showings booked so far, no application submitted yet.",
  },
  {
    id: "job_pm_hartley_duplex",
    name: "Hartley Duplex — Units A & B",
    client: "Hartley Family Trust",
    organizationId: "org_pm_hartley",
    status: "in_progress",
    value: 3200,
    startDate: "2025-03-15",
    dueDate: "2026-03-14",
    ownerId: "emp_pm_carl",
    description: "Side-by-side duplex, 2BR/1BA each unit, both occupied on staggered 12-month leases. Owner Carol Renner requested a rent-comp review ahead of Unit B's upcoming renewal.",
  },
  {
    id: "job_pm_summit_clubhouse",
    name: "Summit Ridge HOA — Clubhouse & Common Areas",
    client: "Summit Ridge HOA",
    organizationId: "org_pm_summit",
    status: "in_progress",
    value: 27000,
    startDate: "2025-07-01",
    dueDate: "2026-06-30",
    ownerId: "emp_pm_diane",
    description: "142-unit HOA community. Full-service management covering landscaping vendor oversight, pool maintenance scheduling, and monthly board meeting support.",
  },
  {
    id: "job_pm_vantage_unit3",
    name: "Vantage Point Fourplex — Unit 3",
    client: "Vantage Point Investments",
    organizationId: "org_pm_vantage",
    status: "scheduled",
    value: 1600,
    startDate: "2026-08-01",
    dueDate: "2027-07-31",
    ownerId: "emp_pm_sofia",
    description: "2BR/2BA, 900 sq ft. New 12-month lease signed; move-in scheduled for August 1 pending the final pre-move walkthrough and key handoff.",
  },
  {
    id: "job_pm_oldmill_retail",
    name: "Old Mill Commons — Retail Suite 2",
    client: "Old Mill Commons LLC",
    organizationId: "org_pm_oldmill",
    status: "done",
    value: 3100,
    startDate: "2026-06-01",
    dueDate: "2026-06-20",
    ownerId: "emp_pm_hector",
    description: "1,400 sq ft ground-floor retail space. Turnover completed on schedule after the prior tenant vacated — new flooring, paint, and an HVAC service call finished ahead of re-listing to prospective retail tenants.",
  },
  {
    id: "job_pm_kestrel_12",
    name: "Kestrel Row Condominiums — Unit 12",
    client: "Kestrel Row Condominiums",
    organizationId: "org_pm_kestrel",
    status: "in_progress",
    value: 1950,
    startDate: "2025-11-15",
    dueDate: "2026-06-30",
    ownerId: "emp_pm_carl",
    overdue: true,
    description: "3BR/2BA condo rental. The original lease term ended June 30; the tenant has stayed on a month-to-month holdover while renewal paperwork is finalized.",
  },
  {
    id: "job_pm_delacroix_fourplex",
    name: "Delacroix Family Properties — 88 Larch Ave Fourplex",
    client: "Delacroix Family Properties",
    organizationId: "org_pm_delacroix",
    status: "in_progress",
    value: 6800,
    startDate: "2025-09-15",
    dueDate: "2026-09-14",
    ownerId: "emp_pm_priya",
    description: "4-unit walk-up, fully occupied. Owner Grant Delacroix is based out of state; the contract includes a mailed monthly owner statement and a quarterly in-person site visit.",
  },
];

const INVOICES: Invoice[] = [
  { id: "inv_pm_1", number: "RENT-3381", client: "Maria Kowalski — Birchwood Unit 4B", amount: 1800, status: "paid", issuedDate: "2026-07-01", dueDate: "2026-07-05" },
  { id: "inv_pm_2", number: "RENT-3382", client: "Lena Ford — Old Mill Commons Unit 2A", amount: 1650, status: "overdue", issuedDate: "2026-06-01", dueDate: "2026-06-05" },
  { id: "inv_pm_3", number: "MGMT-1140", client: "Summit Ridge HOA", amount: 2250, status: "paid", issuedDate: "2026-07-01", dueDate: "2026-07-10" },
  { id: "inv_pm_4", number: "MGMT-1141", client: "Birchwood Holdings LLC", amount: 1600, status: "sent", issuedDate: "2026-07-05", dueDate: "2026-07-20" },
  { id: "inv_pm_5", number: "RENT-3390", client: "Devon Wallace — Kestrel Row Unit 12", amount: 1950, status: "paid", issuedDate: "2026-07-01", dueDate: "2026-07-05" },
  { id: "inv_pm_6", number: "MGMT-1142", client: "Delacroix Family Properties", amount: 1300, status: "sent", issuedDate: "2026-07-05", dueDate: "2026-07-25" },
  { id: "inv_pm_7", number: "RENT-3375", client: "Hartley Duplex — Unit A", amount: 1600, status: "paid", issuedDate: "2026-07-01", dueDate: "2026-07-05" },
  { id: "inv_pm_8", number: "MGMT-1143", client: "Vantage Point Investments", amount: 2875, status: "overdue", issuedDate: "2026-06-01", dueDate: "2026-06-15" },
];

const EMPLOYEES: Employee[] = [
  { id: "emp_pm_diane", name: "Diane Castellano", initials: "DC", title: "Portfolio Manager", department: "Management", email: "diane.castellano@bellhavenpm.com", phone: "(555) 318-2201", hireDate: "2018-04-02", role: "Manager", overdueCount: 0, status: "active" },
  { id: "emp_pm_marcus", name: "Marcus Feld", initials: "MF", title: "Leasing Director", department: "Leasing", email: "marcus.feld@bellhavenpm.com", phone: "(555) 318-3312", hireDate: "2019-09-16", role: "Manager", overdueCount: 0, status: "active" },
  { id: "emp_pm_priya", name: "Priya Anand", initials: "PA", title: "Leasing Agent", department: "Leasing", email: "priya.anand@bellhavenpm.com", phone: "(555) 318-4423", hireDate: "2023-02-06", role: "Member", overdueCount: 1, status: "active" },
  { id: "emp_pm_hector", name: "Hector Salgado", initials: "HS", title: "Maintenance Supervisor", department: "Maintenance", email: "hector.salgado@bellhavenpm.com", phone: "(555) 318-5534", hireDate: "2020-07-20", role: "Manager", overdueCount: 2, overtimeHours: 9, status: "active" },
  { id: "emp_pm_wendy", name: "Wendy Truong", initials: "WT", title: "Maintenance Technician", department: "Maintenance", email: "wendy.truong@bellhavenpm.com", phone: "(555) 318-6645", hireDate: "2022-11-11", role: "Member", overdueCount: 1, status: "active" },
  { id: "emp_pm_owen", name: "Owen Bradshaw", initials: "OB", title: "Accounting Coordinator", department: "Accounting", email: "owen.bradshaw@bellhavenpm.com", phone: "(555) 318-7756", hireDate: "2021-05-03", role: "Member", overdueCount: 0, status: "active" },
  { id: "emp_pm_sofia", name: "Sofia Marchetti", initials: "SM", title: "Assistant Property Manager", department: "Management", email: "sofia.marchetti@bellhavenpm.com", phone: "(555) 318-8867", hireDate: "2024-03-18", role: "Member", overdueCount: 0, status: "away" },
  { id: "emp_pm_carl", name: "Carl Whitfield", initials: "CW", title: "Property Manager", department: "Management", email: "carl.whitfield@bellhavenpm.com", phone: "(555) 318-9978", hireDate: "2017-01-09", role: "Manager", overdueCount: 0, status: "active" },
];

const ACTIVITY: ActivityItem[] = [
  { id: "act_pm_1", message: "Lease renewal offer sent — The Birchwood Apartments Unit 4B (Maria Kowalski)", actor: "Priya Anand", timestamp: "Today", kind: "deal", module: "Leasing" },
  { id: "act_pm_2", message: "Maintenance request submitted — leaking faucet, Kestrel Row Unit 12", actor: "Devon Wallace", timestamp: "This morning", kind: "task", module: "Maintenance" },
  { id: "act_pm_3", message: "Maintenance request resolved — HVAC repair, Delacroix 88 Larch Ave Unit 3", actor: "Hector Salgado", timestamp: "Yesterday", kind: "task", module: "Maintenance" },
  { id: "act_pm_4", message: "Late rent notice sent — Lena Ford, Old Mill Commons Unit 2A", actor: "System", timestamp: "Today", kind: "invoice", module: "Accounting" },
  { id: "act_pm_5", message: "New lease signed — Vantage Point Fourplex Unit 3, move-in Aug 1", actor: "Priya Anand", timestamp: "2 days ago", kind: "deal", module: "Leasing" },
  { id: "act_pm_6", message: "Unit inspection completed — The Birchwood Apartments Unit 6C (pre-listing)", actor: "Sofia Marchetti", timestamp: "3 days ago", kind: "job", module: "Properties" },
  { id: "act_pm_7", message: "Owner statement sent — Vantage Point Investments, June", actor: "Owen Bradshaw", timestamp: "1 week ago", kind: "invoice", module: "Accounting" },
  { id: "act_pm_8", message: "Owner statement sent — Birchwood Holdings LLC, June", actor: "Owen Bradshaw", timestamp: "1 week ago", kind: "invoice", module: "Accounting" },
  { id: "act_pm_9", message: "Turnover completed — Old Mill Commons Retail Suite 2", actor: "Hector Salgado", timestamp: "5 days ago", kind: "job", module: "Properties" },
  { id: "act_pm_10", message: "Management contract renewed — Summit Ridge HOA", actor: "Diane Castellano", timestamp: "2 weeks ago", kind: "deal", module: "CRM" },
  { id: "act_pm_11", message: "New management contract signed — Delacroix Family Properties", actor: "Carl Whitfield", timestamp: "3 weeks ago", kind: "deal", module: "CRM" },
  { id: "act_pm_12", message: "Workflow \"Rent Reminder\" ran for 3 upcoming due dates", actor: "Automation", timestamp: "Today", kind: "automation", module: "Automation" },
  { id: "act_pm_13", message: "Purchase request approved — replacement HVAC condenser, Kestrel Row Condominiums", actor: "Diane Castellano", timestamp: "4 days ago", kind: "approval", module: "Finance" },
  { id: "act_pm_14", message: "Maintenance request submitted — clogged gutter, Hartley Duplex Unit B", actor: "Carol Renner", timestamp: "6 days ago", kind: "task", module: "Maintenance" },
  { id: "act_pm_15", message: "Maintenance request submitted — no hot water, Birchwood Unit 4B", actor: "Maria Kowalski", timestamp: "This morning", kind: "task", module: "Maintenance" },
];

const MONTHLY_RENT_OPS = [
  { month: "Feb", primary: 118200, secondary: 24100 },
  { month: "Mar", primary: 121400, secondary: 26800 },
  { month: "Apr", primary: 119800, secondary: 23500 },
  { month: "May", primary: 124600, secondary: 29200 },
  { month: "Jun", primary: 126900, secondary: 25400 },
  { month: "Jul", primary: 128450, secondary: 27100 },
];

const OCCUPANCY_TREND = [91, 92, 91, 93, 94, 94];

export const PROPERTY_MANAGEMENT_DATASET: IndustryDataset = {
  profileKey: "property_management",
  orgName: "Bellhaven Property Management",
  greetingSubtitle: "Here's what matters at Bellhaven Property Management today.",
  kpis: [
    {
      key: "rent_collected_mtd",
      label: "Rent Collected MTD",
      value: `$${MONTHLY_RENT_OPS[MONTHLY_RENT_OPS.length - 1].primary.toLocaleString()}`,
      deltaLabel: "+1% vs last month",
      tone: "positive",
      trend: MONTHLY_RENT_OPS.map((m) => m.primary),
    },
    {
      key: "occupancy_rate",
      label: "Occupancy Rate",
      value: "94%",
      deltaLabel: "+2 pts vs last month",
      tone: "positive",
      trend: OCCUPANCY_TREND,
    },
    {
      key: "open_maintenance_requests",
      label: "Open Maintenance Requests",
      value: "11",
      deltaLabel: "3 urgent — Birchwood Unit 4B, Hartley Duplex Unit B, Kestrel Row Unit 12",
      tone: "negative",
    },
  ],
  monthlyChart: {
    title: "Rent collected vs. maintenance & operating cost — 6 months",
    primaryLabel: "Rent Collected",
    secondaryLabel: "Maintenance & Ops",
    unit: "currency",
    months: MONTHLY_RENT_OPS,
  },
  breakdownChart: {
    title: "Unit status breakdown",
    segments: [
      { label: "Vacant — Listed", count: JOBS.filter((j) => j.status === "bid").length },
      { label: "Lease Signed — Upcoming Move-in", count: JOBS.filter((j) => j.status === "scheduled").length },
      { label: "Occupied", count: JOBS.filter((j) => j.status === "in_progress").length },
      { label: "Turnover Complete", count: JOBS.filter((j) => j.status === "done").length },
    ],
  },
  organizations: ORGANIZATIONS,
  people: PEOPLE,
  deals: DEALS,
  jobs: JOBS,
  invoices: INVOICES,
  employees: EMPLOYEES,
  notifications: ACTIVITY,
  aiRecommendations: [
    "Old Mill Commons Retail Suite 2 finished turnover 5 days ago and hasn't been re-listed yet — get it back on the market this week before another month of vacancy loss.",
    "Lena Ford's rent at Old Mill Commons Unit 2A (invoice RENT-3382, $1,650) is over a month late — a personal call from Owen Bradshaw tends to resolve these faster than another automated notice.",
    "Vantage Point Investments' management fee invoice (MGMT-1143, $2,875) is overdue while Neil Anders is simultaneously negotiating a 3-building contract expansion — worth collecting on the current invoice before that conversation moves forward.",
    "Kestrel Row Condominiums Unit 12 has been on a month-to-month holdover since its June 30 lease end — send the renewal paperwork this week so Carl Whitfield isn't managing it without a signed lease going into August.",
  ],
};
