import type {
  ActivityItem,
  Deal,
  Employee,
  IndustryDataset,
  Invoice,
  Job,
  Organization,
  Person,
} from "@/types";

// ---- Vantage Point Security Services ----
// Contract guard services for office parks, retail centers, warehouses,
// apartment communities, a hospital campus, and event venues. All data below
// is hand-authored for this industry — nothing is imported or shared with
// other industry datasets.

const ORGANIZATIONS: Organization[] = [
  { id: "org_sec_crescent", name: "Crescent Corporate Park", domain: "crescentcorporatepark.com", industry: "Commercial Real Estate", ownerId: "emp_sec_monroe", createdAt: "2024-09-12" },
  { id: "org_sec_parkway", name: "Parkway Plaza Shopping Center", domain: "parkwayplazashops.com", industry: "Retail", ownerId: "emp_sec_monroe", createdAt: "2024-11-05" },
  { id: "org_sec_unionfreight", name: "Union Freight Logistics", domain: "unionfreightlogistics.com", industry: "Logistics & Distribution", ownerId: "emp_sec_alvarez", createdAt: "2025-01-20" },
  { id: "org_sec_aldridge", name: "The Aldridge at Riverbend", domain: "aldridgeriverbend.com", industry: "Multifamily Residential", ownerId: "emp_sec_alvarez", createdAt: "2025-02-14" },
  { id: "org_sec_staugustine", name: "St. Augustine Medical Center", domain: "staugustinemedical.org", industry: "Healthcare", ownerId: "emp_sec_monroe", createdAt: "2024-05-01" },
  { id: "org_sec_ember", name: "Ember Live Event Hall", domain: "emberliveeventhall.com", industry: "Events & Entertainment", ownerId: "emp_sec_carver", createdAt: "2025-06-10" },
  { id: "org_sec_kingsley", name: "Kingsley Court Apartments", domain: "kingsleycourtapts.com", industry: "Multifamily Residential", ownerId: "emp_sec_alvarez", createdAt: "2024-08-01" },
  { id: "org_sec_brightline", name: "Brightline Business Center", domain: "brightlinebusinesscenter.com", industry: "Commercial Real Estate", ownerId: "emp_sec_carver", createdAt: "2026-05-15" },
  { id: "org_sec_northshore", name: "Northshore Collection", domain: "northshorecollection.com", industry: "Retail", ownerId: "emp_sec_carver", createdAt: "2026-06-20" },
];

const PEOPLE: Person[] = [
  { id: "per_sec_hale", firstName: "Brian", lastName: "Hale", email: "brian.hale@crescentcorporatepark.com", phone: "(555) 604-1187", organizationId: "org_sec_crescent", personType: "customer", ownerId: "emp_sec_monroe", createdAt: "2024-09-12", lastContact: "5 days ago" },
  { id: "per_sec_odonnell", firstName: "Megan", lastName: "O'Donnell", email: "megan.odonnell@parkwayplazashops.com", phone: "(555) 604-2298", organizationId: "org_sec_parkway", personType: "customer", ownerId: "emp_sec_monroe", createdAt: "2024-11-05", lastContact: "1 week ago" },
  { id: "per_sec_delgado", firstName: "Victor", lastName: "Delgado", email: "victor.delgado@unionfreightlogistics.com", phone: "(555) 604-3309", organizationId: "org_sec_unionfreight", personType: "customer", ownerId: "emp_sec_alvarez", createdAt: "2025-01-20", lastContact: "Today" },
  { id: "per_sec_shaw", firstName: "Natalie", lastName: "Shaw", email: "natalie.shaw@aldridgeriverbend.com", phone: "(555) 604-4410", organizationId: "org_sec_aldridge", personType: "customer", ownerId: "emp_sec_alvarez", createdAt: "2025-02-14", lastContact: "4 days ago" },
  { id: "per_sec_bennett", firstName: "Howard", lastName: "Bennett", email: "h.bennett@staugustinemedical.org", phone: "(555) 604-5521", organizationId: "org_sec_staugustine", personType: "customer", ownerId: "emp_sec_monroe", createdAt: "2024-05-01", lastContact: "2 days ago" },
  { id: "per_sec_reyna", firstName: "Isabel", lastName: "Reyna", email: "isabel.reyna@emberliveeventhall.com", phone: "(555) 604-6632", organizationId: "org_sec_ember", personType: "customer", ownerId: "emp_sec_carver", createdAt: "2025-06-10", lastContact: "Yesterday" },
  { id: "per_sec_castillo", firstName: "Marisol", lastName: "Castillo", email: "marisol.castillo@kingsleycourtapts.com", phone: "(555) 604-7743", organizationId: "org_sec_kingsley", personType: "customer", ownerId: "emp_sec_alvarez", createdAt: "2024-08-01", lastContact: "3 weeks ago" },
  { id: "per_sec_lindgren", firstName: "Erik", lastName: "Lindgren", email: "erik.lindgren@brightlinebusinesscenter.com", phone: "(555) 604-8854", organizationId: "org_sec_brightline", personType: "lead", ownerId: "emp_sec_carver", createdAt: "2026-05-15", lastContact: "Yesterday" },
  { id: "per_sec_pruitt", firstName: "Todd", lastName: "Pruitt", email: "todd.pruitt@northshorecollection.com", phone: "(555) 604-9965", organizationId: "org_sec_northshore", personType: "lead", ownerId: "emp_sec_carver", createdAt: "2026-06-20", lastContact: "2 days ago" },
];

const DEALS: Deal[] = [
  { id: "deal_sec_crescent", personId: "per_sec_hale", organizationId: "org_sec_crescent", title: "Crescent Corporate Park Overnight Patrol Contract", value: 96000, stage: "won", ownerId: "emp_sec_monroe", expectedCloseDate: "2024-09-25" },
  { id: "deal_sec_parkway", personId: "per_sec_odonnell", organizationId: "org_sec_parkway", title: "Parkway Plaza Shopping Center Security Contract", value: 132000, stage: "won", ownerId: "emp_sec_monroe", expectedCloseDate: "2024-11-20" },
  { id: "deal_sec_unionfreight", personId: "per_sec_delgado", organizationId: "org_sec_unionfreight", title: "Union Freight Logistics Warehouse Security Contract", value: 84000, stage: "won", ownerId: "emp_sec_alvarez", expectedCloseDate: "2025-02-10" },
  { id: "deal_sec_aldridge", personId: "per_sec_shaw", organizationId: "org_sec_aldridge", title: "The Aldridge at Riverbend Gatehouse & Patrol Contract", value: 64800, stage: "won", ownerId: "emp_sec_alvarez", expectedCloseDate: "2025-02-25" },
  { id: "deal_sec_staugustine", personId: "per_sec_bennett", organizationId: "org_sec_staugustine", title: "St. Augustine Medical Center Campus Security Contract", value: 156000, stage: "won", ownerId: "emp_sec_monroe", expectedCloseDate: "2024-05-20" },
  { id: "deal_sec_ember", personId: "per_sec_reyna", organizationId: "org_sec_ember", title: "Ember Live Event Hall Overflow Security Contract", value: 28000, stage: "won", ownerId: "emp_sec_carver", expectedCloseDate: "2025-06-25" },
  { id: "deal_sec_kingsley", personId: "per_sec_castillo", organizationId: "org_sec_kingsley", title: "Kingsley Court Apartments Courtesy Patrol Contract", value: 46800, stage: "won", ownerId: "emp_sec_alvarez", expectedCloseDate: "2024-08-15" },
  { id: "deal_sec_brightline", personId: "per_sec_lindgren", organizationId: "org_sec_brightline", title: "Brightline Business Center Overnight Patrol Contract", value: 54000, stage: "negotiation", ownerId: "emp_sec_carver", expectedCloseDate: "2026-08-05" },
  { id: "deal_sec_northshore", personId: "per_sec_pruitt", organizationId: "org_sec_northshore", title: "Northshore Collection Mall Security Contract", value: 168000, stage: "new_lead", ownerId: "emp_sec_carver", expectedCloseDate: "2026-10-15" },
  { id: "deal_sec_crescent_upsell", personId: "per_sec_hale", organizationId: "org_sec_crescent", title: "Crescent Corporate Park Weekend Patrol Add-On", value: 18000, stage: "proposal", ownerId: "emp_sec_monroe", expectedCloseDate: "2026-08-01" },
];

const JOBS: Job[] = [
  {
    id: "job_sec_crescent",
    name: "Crescent Corporate Park — Overnight Patrol",
    client: "Crescent Corporate Park",
    organizationId: "org_sec_crescent",
    status: "in_progress",
    value: 96000,
    startDate: "2024-10-01",
    dueDate: "2026-10-01",
    ownerId: "emp_sec_monroe",
    description: "Two unarmed guards nightly, 6 PM-6 AM, covering the three-building office park and parking structure; includes perimeter lock-up and an after-hours visitor log for tenants.",
  },
  {
    id: "job_sec_parkway",
    name: "Parkway Plaza Shopping Center — Day & Evening Coverage",
    client: "Parkway Plaza Shopping Center",
    organizationId: "org_sec_parkway",
    status: "in_progress",
    value: 132000,
    startDate: "2024-12-01",
    dueDate: "2026-12-01",
    ownerId: "emp_sec_monroe",
    description: "Three unarmed guards rotating 10 AM-11 PM, seven days a week, plus a mobile patrol vehicle covering the outer lots and loading docks.",
  },
  {
    id: "job_sec_unionfreight",
    name: "Union Freight Logistics — Warehouse Security",
    client: "Union Freight Logistics",
    organizationId: "org_sec_unionfreight",
    status: "in_progress",
    value: 84000,
    startDate: "2025-02-15",
    dueDate: "2026-08-15",
    ownerId: "emp_sec_alvarez",
    overdue: true,
    description: "Two unarmed guards covering the loading dock and yard gate across three rotating shifts, with gate-log and delivery verification duties. Currently short one guard on the overnight shift after a call-out.",
  },
  {
    id: "job_sec_aldridge",
    name: "The Aldridge at Riverbend — Gatehouse & Courtesy Patrol",
    client: "The Aldridge at Riverbend",
    organizationId: "org_sec_aldridge",
    status: "in_progress",
    value: 64800,
    startDate: "2025-03-01",
    dueDate: "2026-09-01",
    ownerId: "emp_sec_alvarez",
    description: "One guard staffing the gatehouse 4 PM-12 AM daily, plus two weekly courtesy patrols of the parking garage and pool area for the 340-unit community.",
  },
  {
    id: "job_sec_staugustine",
    name: "St. Augustine Medical Center — Campus Security",
    client: "St. Augustine Medical Center",
    organizationId: "org_sec_staugustine",
    status: "in_progress",
    value: 156000,
    startDate: "2024-06-01",
    dueDate: "2026-12-01",
    ownerId: "emp_sec_monroe",
    description: "Four guards covering the ER entrance, main lobby, and parking structure around the clock. The ER entrance post is armed per hospital policy; remaining posts are unarmed with visitor-screening duties.",
  },
  {
    id: "job_sec_ember",
    name: "Ember Live Event Hall — Overflow Event Security",
    client: "Ember Live Event Hall",
    organizationId: "org_sec_ember",
    status: "scheduled",
    value: 28000,
    startDate: "2026-07-18",
    dueDate: "2027-01-18",
    ownerId: "emp_sec_carver",
    description: "On-call staffing of 6-10 unarmed guards per event for concerts and private functions of 800+ attendees. The next event, a July 18 concert, is fully staffed and confirmed.",
  },
  {
    id: "job_sec_kingsley",
    name: "Kingsley Court Apartments — Courtesy Patrol",
    client: "Kingsley Court Apartments",
    organizationId: "org_sec_kingsley",
    status: "done",
    value: 46800,
    startDate: "2024-08-01",
    dueDate: "2026-06-30",
    ownerId: "emp_sec_alvarez",
    description: "Nightly courtesy patrol contract. The HOA board voted not to renew after standing up an in-house volunteer courtesy patrol program; final invoice closed out in June.",
  },
  {
    id: "job_sec_brightline",
    name: "Brightline Business Center — Overnight Patrol (Proposed)",
    client: "Brightline Business Center",
    organizationId: "org_sec_brightline",
    status: "bid",
    value: 54000,
    startDate: "2026-09-01",
    dueDate: "2026-09-01",
    ownerId: "emp_sec_carver",
    description: "Proposal submitted for one unarmed guard, 8 PM-6 AM nightly, covering the four-building business center and shared parking deck. Awaiting a decision from property management.",
  },
  {
    id: "job_sec_northshore",
    name: "Northshore Collection — Mall Security (Proposed)",
    client: "Northshore Collection",
    organizationId: "org_sec_northshore",
    status: "bid",
    value: 168000,
    startDate: "2026-10-01",
    dueDate: "2026-10-01",
    ownerId: "emp_sec_carver",
    description: "Early-stage proposal for a five-guard rotation covering common areas, the food court, and the parking structure at the 620,000 sq ft regional mall. Site walk complete; formal RFP response due end of month.",
  },
];

const INVOICES: Invoice[] = [
  { id: "inv_sec_2101", number: "INV-2101", client: "Crescent Corporate Park", amount: 8000, status: "paid", issuedDate: "2026-06-01", dueDate: "2026-06-15" },
  { id: "inv_sec_2102", number: "INV-2102", client: "Parkway Plaza Shopping Center", amount: 11000, status: "sent", issuedDate: "2026-07-01", dueDate: "2026-07-15" },
  { id: "inv_sec_2103", number: "INV-2103", client: "Union Freight Logistics", amount: 7000, status: "overdue", issuedDate: "2026-06-11", dueDate: "2026-06-26" },
  { id: "inv_sec_2104", number: "INV-2104", client: "The Aldridge at Riverbend", amount: 5400, status: "paid", issuedDate: "2026-06-01", dueDate: "2026-06-15" },
  { id: "inv_sec_2105", number: "INV-2105", client: "St. Augustine Medical Center", amount: 13000, status: "sent", issuedDate: "2026-07-01", dueDate: "2026-07-20" },
  { id: "inv_sec_2106", number: "INV-2106", client: "Ember Live Event Hall", amount: 14000, status: "sent", issuedDate: "2026-07-05", dueDate: "2026-07-25" },
  { id: "inv_sec_2107", number: "INV-2107", client: "Kingsley Court Apartments", amount: 3900, status: "paid", issuedDate: "2026-06-15", dueDate: "2026-06-30" },
];

const EMPLOYEES: Employee[] = [
  {
    id: "emp_sec_monroe",
    name: "Derek Monroe",
    initials: "DM",
    title: "Operations Manager",
    department: "Operations",
    email: "derek.monroe@vantagepointsecurity.com",
    phone: "(555) 318-1140",
    hireDate: "2021-05-10",
    role: "Manager",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_sec_carver",
    name: "Samantha Carver",
    initials: "SC",
    title: "Business Development Manager",
    department: "Business Development",
    email: "samantha.carver@vantagepointsecurity.com",
    phone: "(555) 318-2251",
    hireDate: "2023-02-06",
    role: "Manager",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_sec_alvarez",
    name: "Christina Alvarez",
    initials: "CA",
    title: "Site Supervisor",
    department: "Field",
    email: "christina.alvarez@vantagepointsecurity.com",
    phone: "(555) 318-3362",
    hireDate: "2022-08-19",
    role: "Manager",
    overdueCount: 1,
    overtimeHours: 6,
    status: "active",
  },
  {
    id: "emp_sec_park",
    name: "Jason Park",
    initials: "JP",
    title: "Lead Guard",
    department: "Field",
    email: "jason.park@vantagepointsecurity.com",
    phone: "(555) 318-4473",
    hireDate: "2026-06-15",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_sec_whitfield",
    name: "Renee Whitfield",
    initials: "RW",
    title: "Scheduling Coordinator",
    department: "Admin",
    email: "renee.whitfield@vantagepointsecurity.com",
    phone: "(555) 318-5584",
    hireDate: "2024-03-12",
    role: "Member",
    overdueCount: 1,
    status: "active",
  },
  {
    id: "emp_sec_dubois",
    name: "Marcus Dubois",
    initials: "MD",
    title: "Compliance Officer",
    department: "Compliance",
    email: "marcus.dubois@vantagepointsecurity.com",
    phone: "(555) 318-6695",
    hireDate: "2022-01-24",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
  {
    id: "emp_sec_nakamura",
    name: "Aiko Nakamura",
    initials: "AN",
    title: "Guard",
    department: "Field",
    email: "aiko.nakamura@vantagepointsecurity.com",
    phone: "(555) 318-7706",
    hireDate: "2024-09-09",
    role: "Member",
    overdueCount: 0,
    status: "away",
  },
  {
    id: "emp_sec_hollis",
    name: "Patricia Hollis",
    initials: "PH",
    title: "Billing & Accounts Coordinator",
    department: "Admin",
    email: "patricia.hollis@vantagepointsecurity.com",
    phone: "(555) 318-8817",
    hireDate: "2023-06-15",
    role: "Member",
    overdueCount: 0,
    status: "active",
  },
];

const NOTIFICATIONS: ActivityItem[] = [
  { id: "act_sec_1", message: "Guard call-out on the overnight shift at Union Freight Logistics — Aiko Nakamura out sick", actor: "Renee Whitfield", timestamp: "Today", kind: "task", module: "Projects" },
  { id: "act_sec_2", message: "Incident report filed: gate arm malfunction at the Union Freight Logistics loading dock", actor: "Christina Alvarez", timestamp: "Today", kind: "document", module: "Documents" },
  { id: "act_sec_3", message: "Union Freight Logistics flagged the overnight coverage gap on today's check-in call", actor: "Victor Delgado", timestamp: "Today", kind: "message", module: "Communications" },
  { id: "act_sec_4", message: "Overtime approved to backfill the Union Freight Logistics overnight post", actor: "Derek Monroe", timestamp: "Today", kind: "approval", module: "Finance" },
  { id: "act_sec_5", message: "Invoice INV-2103 (Union Freight Logistics) is now 12 days overdue", actor: "System", timestamp: "Today", kind: "invoice", module: "Finance" },
  { id: "act_sec_6", message: "Workflow \"Overdue Invoice Reminder\" ran for INV-2103", actor: "Automation", timestamp: "Today", kind: "automation", module: "Automation" },
  { id: "act_sec_7", message: "Trespass incident logged and resolved at Parkway Plaza Shopping Center — subject escorted off property", actor: "Jason Park", timestamp: "Yesterday", kind: "document", module: "Documents" },
  { id: "act_sec_8", message: "St. Augustine Medical Center praised the ER entrance guard for de-escalating a visitor dispute", actor: "Howard Bennett", timestamp: "2 days ago", kind: "message", module: "Communications" },
  { id: "act_sec_9", message: "Brightline Business Center walkthrough complete — deal moved to Negotiation", actor: "Samantha Carver", timestamp: "Yesterday", kind: "deal", module: "CRM" },
  { id: "act_sec_10", message: "Northshore Collection added to the pipeline as a new lead", actor: "Samantha Carver", timestamp: "2 days ago", kind: "deal", module: "CRM" },
  { id: "act_sec_11", message: "Crescent Corporate Park requested a proposal for weekend patrol coverage", actor: "Brian Hale", timestamp: "5 days ago", kind: "deal", module: "CRM" },
  { id: "act_sec_12", message: "State guard license renewals completed for 4 field staff", actor: "Marcus Dubois", timestamp: "3 days ago", kind: "approval", module: "People" },
  { id: "act_sec_13", message: "Uploaded June patrol logs for Parkway Plaza Shopping Center", actor: "Jason Park", timestamp: "3 days ago", kind: "document", module: "Documents" },
  { id: "act_sec_14", message: "Job marked Done — Kingsley Court Apartments courtesy patrol contract ended", actor: "Christina Alvarez", timestamp: "1 week ago", kind: "job", module: "Projects" },
  { id: "act_sec_15", message: "Final invoice INV-2107 (Kingsley Court Apartments) paid in full", actor: "System", timestamp: "1 week ago", kind: "invoice", module: "Finance" },
  { id: "act_sec_16", message: "Scheduled: Brightline Business Center contract walkthrough", actor: "Samantha Carver", timestamp: "4 days ago", kind: "meeting", module: "Meetings" },
  { id: "act_sec_17", message: "Ember Live Event Hall confirmed staffing for the July 18 concert — 8 guards assigned", actor: "Isabel Reyna", timestamp: "Yesterday", kind: "message", module: "Communications" },
  { id: "act_sec_18", message: "Jason Park started as Lead Guard", actor: "Derek Monroe", timestamp: "3 weeks ago", kind: "hire", module: "People" },
];

const CONTRACT_REVENUE_MONTHS = [
  { month: "Feb", primary: 498000, secondary: 351000 },
  { month: "Mar", primary: 505000, secondary: 354000 },
  { month: "Apr", primary: 512000, secondary: 358000 },
  { month: "May", primary: 519000, secondary: 362000 },
  { month: "Jun", primary: 530000, secondary: 366000 },
  { month: "Jul", primary: 551000, secondary: 378000 },
];

const CONTRACT_REVENUE_MTD = CONTRACT_REVENUE_MONTHS[CONTRACT_REVENUE_MONTHS.length - 1].primary;
const GUARD_COVERAGE_TREND = [96, 95, 94, 93, 91, 89];
const openSites = JOBS.filter((j) => j.status === "in_progress" || j.status === "scheduled");

export const SECURITY_DATASET: IndustryDataset = {
  profileKey: "security",
  orgName: "Vantage Point Security Services",
  greetingSubtitle: "Here's what matters at Vantage Point Security Services today.",
  kpis: [
    {
      key: "contract_revenue_mtd",
      label: "Contract Revenue MTD",
      value: `$${CONTRACT_REVENUE_MTD.toLocaleString()}`,
      deltaLabel: "+4% vs last month",
      tone: "positive",
      trend: CONTRACT_REVENUE_MONTHS.map((m) => m.primary),
    },
    {
      key: "guard_coverage_pct",
      label: "Guard Coverage %",
      value: "89%",
      deltaLabel: "1 open post — Union Freight Logistics overnight shift",
      tone: "negative",
      trend: GUARD_COVERAGE_TREND,
    },
    {
      key: "open_incidents",
      label: "Open Incidents",
      value: "3",
      deltaLabel: "Includes 1 unresolved coverage gap — Union Freight Logistics",
      tone: "negative",
    },
  ],
  monthlyChart: {
    title: "Contract revenue vs. payroll cost — 6 months",
    primaryLabel: "Contract Revenue",
    secondaryLabel: "Payroll Cost",
    unit: "currency",
    months: CONTRACT_REVENUE_MONTHS,
  },
  breakdownChart: {
    title: "Site coverage status",
    segments: [
      { label: "Prospective Site", count: JOBS.filter((j) => j.status === "bid").length },
      { label: "Contract Signed — Awaiting Start", count: JOBS.filter((j) => j.status === "scheduled").length },
      { label: "Active Coverage", count: JOBS.filter((j) => j.status === "in_progress").length },
      { label: "Contract Ended", count: JOBS.filter((j) => j.status === "done").length },
    ],
  },
  organizations: ORGANIZATIONS,
  people: PEOPLE,
  deals: DEALS,
  jobs: JOBS,
  invoices: INVOICES,
  employees: EMPLOYEES,
  notifications: NOTIFICATIONS,
  aiRecommendations: [
    "Union Freight Logistics has an open overnight post after Aiko Nakamura's call-out and is also 12 days past due on INV-2103 — a single call from Derek Monroe covering both the coverage gap and the invoice will land better than two separate emails.",
    "Union Freight Logistics renews August 15, and its only open incident and overdue invoice landed the same week Kingsley Court Apartments chose not to renew for similar service complaints — closing the coverage gap now protects an $84,000 contract from following the same path.",
    "Brightline Business Center has been in Negotiation with Erik Lindgren for several weeks — Samantha Carver should use the guard capacity freed up by the completed Kingsley Court contract to sweeten the proposal and close before the prospect solicits competing bids.",
    `Guard coverage has slipped from ${GUARD_COVERAGE_TREND[0]}% to ${GUARD_COVERAGE_TREND[GUARD_COVERAGE_TREND.length - 1]}% over the past ${GUARD_COVERAGE_TREND.length} months while Northshore Collection is asking for a 5-guard rotation across ${openSites.length} active sites already running — hire 2-3 guards before committing to Northshore's October start date so the bench doesn't stretch as thin as it did at Union Freight.`,
  ],
};
